# Site settings
title: Step By Step
author: jokin
email: 345106552@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: jekyllrb
github_username:  jekyll
domain: "http://yourdomain.com" # the base hostname & protocol for your site

# Site URL NOTE: end with / cause it's [URL + FILE]
base_url: "" # the subpath of your site, eg. "/blog/"
w3c_url: "/w3c/"  # the base url of css js and images
postImage_url: "/w3c/images/" # the base url of post images
postfile: "/Postfile" # the Database

# 3rd URL
duoshuo_user: "jokin" # the user of user.domain.com
duoshuo_path: "/w3c/duoshuo/" # the local duoshuo comment plugin, you can change it to remote "http://static.duoshuo.com/"
jquery_url: "//cdn.bootcss.com/jquery/3.1.0/jquery.min.js" # use cdn
baiduTemplate_url: "/w3c/js/baiduTemplate.js" #use local

# Build Settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
