title:            Blog Of CuiCui
description:      Just work much harder !
url:              
baseurl:          www.cuicui.info # Base url. ( if use subdirectory-like URL )
signoff:          cuicui # Your name.
disqus_shortname: cuicui # disqus comment thread for post header options. ( leave blank if unwanted. )
google_analytics_id: # set tracking, UA-XXXX-Y.
encoding: utf-8
links:
  
  - name:         Blog
    url:          /
  - name:         Categories
    url:          /tags
  - name:         GitHub
    url:          http://github.com/hello-xk
    external:     true
  - name:         About
    url:          /about

pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:     [autolink, tables]
