title:            Blog Of Helloxk
description:      Just work much harder !
url:              
baseurl:          # Base url. ( if use subdirectory-like URL )
signoff:          helloxk # Your name.
google_analytics_id: # set tracking, UA-XXXX-Y.
encoding: utf-8
links:
  
  - name:         Blog
    url:          /
  - name:         Categories
    url:          /tags
  - name:         GitHub
    url:          http://github.com/hello-xk
    external:     true
  - name:         About
    url:          /about
  - name:         MyCV 
    url:          /me/jianli.html

highlighter:      pygments
pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:     [autolink, tables]
comments:
   provider:    uyan 
