# Site settings
title: Step By Step
author: jokin
email: 345106552@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: jekyllrb
github_username:  jekyll

# Size URL
domain: "http://yourdomain.com" # the base hostname & protocol for your site
base_url: "" # the subpath of your site, eg. "/blog" NOT "yourdomain.com/"
w3c_url: "/w3c/"  # the base url of css js and images
duoshuo_url: "/w3c/duoshuo/" # the local duoshuo comment plugin, you can change it to remote "http://static.duoshuo.com/"
duoshuo_user: "jokin" # the user of user.domain.com
jquery_url: "//cdn.bootcss.com/jquery/3.1.0/" # use cdn
postfile: "/Postfile" # the Database

# Build Settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
